### ISSUE TITLE
Package installation problem

### ISSUE THREAD

**Issue by KarlKaise** [portrai-io/CELLama#1]
Hello,

Upon trying to install the package I encountered following error message:

(Cellama_env) -bash-4.2$ pip install git+https://github.com/portrai-io/CELLama.git
Collecting git+https://github.com/portrai-io/CELLama.git
  Cloning https://github.com/portrai-io/CELLama.git to /scratch/pip-req-build-vkn63s40
  Running command git clone --quiet https://github.com/portrai-io/CELLama.git /scratch/pip-req-build-vkn63s40
  Resolved https://github.com/portrai-io/CELLama.git to commit 7337e165edfbc8d63891c0319b68f9def485f9be
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      error: Multiple top-level packages discovered in a flat-layout: ['notebooks', 'cellama_st', 'cellama_training'].

      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.

      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:

      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names

      To find more information, look for "package discovery" on setuptools docs.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Is the problem that I try to install the package withing mamba env with Python 3.9?

Thank you in advance for any help.

**Comment by shobhitagrawal1** [comment]
same as above, help would be appreciated ! Thank you

**Comment by JB243** [comment]
To @KarlKaise  and @shobhitagrawal1,
Please follow these steps as outlined in the updated `README.md`

```bash
### Successful on Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-105-generic x86_64)

conda create --name cellama2 python=3.9
conda activate cellama2
python --version
# Python 3.9.19
git clone https://github.com/portrai-io/CELLama.git 
cd CELLama
pip install -r requirements.txt

### OPTIONAL
pip install ipykernel jupyter jupyterlab 
python -m ipykernel install --user --name CELLama --display-name CELLama
cd
jupyter lab
```

**Comment by chy-portrai** [comment]
The installation process has been updated and verified to work. You can install directly using:

pip install git+https://github.com/portrai-io/CELLama.git

Alternatively, after downloading, you can install it locally with editable mode enabled:
pip install -e .


For more detailed instructions, please refer to the updated README.md.

**Comment by KarlKaise** [comment]
Works perfectly. Thank you !!
